FROM tensorflow/tensorflow:1.15.4-gpu-py3

WORKDIR /app

ENV LANG=C.UTF-8

RUN apt-get update -y && apt-get install -y \
    git \
    wget \
    curl \
    cmake \
    unzip \
    gcc \
    g++ \
    mecab libmecab-dev  \
    python3-numpy python3-scipy python3-pip
RUN ln -s /etc/mecabrc /usr/local/etc/mecabrc

RUN pip3 install --upgrade pip && \
    pip install tokenizers mecab-python3 ipadic

COPY build_pretraining_dataset_hf.py /app/

COPY model /app/model
COPY pretrain /app/pretrain
COPY util /app/util

COPY run_pretraining.sh run_pretraining.py configure_pretraining.py tokenization_hf.py /app/
RUN mkdir -p outputs/models

CMD ["bash", "run_pretraining.sh"]