FROM huggingface/transformers-tensorflow-cpu

WORKDIR /app

ENV LANG=C.UTF-8

RUN apt-get update -y && apt-get install -y \
    git \
    wget \
    curl \
    cmake \
    unzip \
    gcc \
    g++ \
    python3-pip

RUN pip3 install --upgrade pip && \
    pip install tokenizers

COPY convert_pytorch.py configure_pretraining.py /app/

CMD ["python3", "convert_pytorch.py"]