FROM nvidia/cuda:11.1-cudnn8-runtime-ubuntu18.04

WORKDIR /app

ENV LANG=C.UTF-8

RUN apt-get update -y && apt-get install -y \
    git \
    wget \
    curl \
    cmake \
    unzip \
    gcc \
    g++ \
    python3-numpy python3-scipy python3-pip

RUN pip3 install --upgrade pip && \
    pip install tensorflow-gpu==1.15 scikit-learn tokenizers

COPY run_tfrecords.sh build_pretraining_dataset_hf.py tokenization_hf.py /app/
RUN mkdir -p outputs/data
RUN mkdir -p outputs/models

CMD ["bash", "run_tfrecords.sh"]